build_from:
  amd64: docker.io/library/python:3.12-alpine
  aarch64: docker.io/library/python:3.12-alpine
labels:
  io.hass.name: "SigEnergy Optimizer"
  io.hass.description: "SigEnergy optimizer with dashboard and HA control"
  io.hass.type: "addon"
  io.hass.version: "2.1.99-haos21"
